# Get all
GET http://localhost:3001/api/projects
Content-Type: application/json
###

# Insert
POST http://localhost:3001/api/projects
Content-Type: application/json
 
{
    "title": "Project One",
    "detais": "No detais",
    "beginDate": "10 Oct 2020 14:00:00 GMT",
    "endDate": "14 Oct 2020 14:00:00 GMT",
    "demandantName": "João",
    "demandantEmail": "joao@email.com"
}
###