# Get all
GET http://localhost:3001/api/users
Content-Type: application/json
###


# Insert
POST http://localhost:3001/api/users
Content-Type: application/json
 
{
    "name": "Pedro", 
    "email": "pedro@email.com",
    "occupation": "Programmer"
}
###
